lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-lrsomatic_logo_light.png
    - docs/images/nf-core-lrsomatic_logo_light.png
    - docs/images/nf-core-lrsomatic_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-lrsomatic_logo_light.png
    - docs/images/nf-core-lrsomatic_logo_light.png
    - docs/images/nf-core-lrsomatic_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  schema_params: false
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Jonas Demeulemeester
  description: Workflow for somatic variant calling of long read data
  force: false
  is_nfcore: false
  name: lrsomatic
  org: IntGenomicsLab
  outdir: .
  skip_features:
    - fastqc
  version: 1.0.0dev
