---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fibertoolsrs_predictm6a"
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
keywords:
  - sort
  - example
  - genomics
tools:
  - "fibertoolsrs":
      ## TODO nf-core: Add a description and other details for the software below
      description: "Mitchell Vollger's rust tools for fiberseq data."
      homepage: "https://fiberseq.github.io/fibertools/fibertools.html"
      documentation: "https://fiberseq.github.io/fibertools/fibertools.html"
      tool_dev_url: "https://github.com/fiberseq/fibertools-rs"
      doi: ""
      licence: ['MIT']
      identifier: 

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  
  ## TODO nf-core: Delete / customise this example input
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
          

## TODO nf-core: Add a description of all of the variables used as output
output:
  - bam:
  #Only when we have meta
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  ## TODO nf-core: Delete / customise this example output
    - "*.bam":
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@MariosEft97"
maintainers:
  - "@MariosEft97"
