---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fibertoolsrs_qc"
description: Fibertools-rs qc generates quality control statistics for fiber-seq BAM files
keywords:
  - fiberseq
  - qc
  - quality-control
  - long-read
  - epigenetics
tools:
  - "fibertoolsrs":
      description: "DNA-m6A calling and integrated long-read epigenetic and genetic analysis with fibertools"
      homepage: "https://fiberseq.github.io/fibertools/fibertools.html"
      documentation: "https://fiberseq.github.io/fibertools/fibertools.html"
      tool_dev_url: "https://github.com/fiberseq/fibertools-rs"
      doi: "10.1101/gr.279095.124"
      licence: ["MIT"]

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bam:
        type: file
        description: Sorted BAM/CRAM/SAM file
        pattern: "*.{bam,cram,sam}"
        ontologies:
          - edam: "http://edamontology.org/format_25722"
          - edam: "http://edamontology.org/format_2573"
          - edam: "http://edamontology.org/format_3462"

output:
  qc_txt:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - "*.txt":
        type: file
        description: QC text file
        pattern: "*.txt"
  versions_fibertoolsrs:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - fibertoolsrs:
          type: string
          description: The tool name
      - "ft --version |& sed '1!d ; s/ft //'":
          type: string
          description: The command used to generate the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The process the versions were collected from
      - fibertoolsrs:
          type: string
          description: The tool name
      - "ft --version |& sed '1!d ; s/ft //'":
          type: string
          description: The command used to generate the version of the tool

authors:
  - "@MariosEft97"
maintainers:
  - "@MariosEft97"
